<a href="https://colab.research.google.com/github/giladgavlovski/beyondthehype/blob/master/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sklearn
sklearn.__version__

'0.22.2.post1'

In [0]:
import pandas as pd
df = pd.read_csv('http://bit.ly/kaggletrain', nrows=10)

In [4]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [5]:
X = df[['Parch', 'Survived']] # two brackets creates a data frame
X

Parch  Survived
0      0         0
1      0         1
2      0         1
3      0         1
4      0         0
5      0         0
6      0         0
7      1         0
8      2         1
9      0         1

In [6]:
X.shape #in caps because it's 2 dimensions

(10, 2)

In [7]:
y = df['Survived'] #single bracket creates a series
y

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [8]:
y.shape

(10,)

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
logreg = LogisticRegression(solver = 'liblinear', random_state = 1)

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(logreg, X, y, cv=3, scoring='accuracy').mean()

1.0

In [12]:
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
df_new = pd.read_csv('http://bit.ly/kaggletest', nrows=10)
df_new

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S
5          897       3  ...   NaN        S
6          898       3  ...   NaN        Q
7          899       2  ...   NaN        S
8          900       3  ...   NaN        C
9          901       3  ...   NaN        S

[10 rows x 11 columns]

In [14]:
X_new = df_new[['Parch', 'Fare']]
X_new

Parch     Fare
0      0   7.8292
1      0   7.0000
2      0   9.6875
3      0   8.6625
4      1  12.2875
5      0   9.2250
6      0   7.6292
7      1  29.0000
8      0   7.2292
9      0  24.1500

In [15]:
logreg.predict(X_new)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
# Encoding the categorical features

In [26]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit_transform(df[['Embarked']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [19]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [20]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
#fit is when it learns something from the data
#transform is when it uses what it learned, to actually do the transformation
#we could have done first ohe.fit and then ohe.transform but ohe.fit_transform lo hace en un paso los dos que es normalmente lo mejor. 

In [22]:
#this command was already execute before but here we are just pointing out that it's important to 
#remember to give the double bracket so that it considers it as a column, instead of a series. 
#A series looks like a column, but it is actually a one dimensional object, whereas a dataframe with one column 
#is considered a two dimensional object. 

ohe.fit_transform(df[['Embarked']]) 

<10x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [27]:
ohe.fit_transform(df[['Embarked', 'Sex']]) 

#first 3 columns are enconding Embarked and last 2 are encoding Sex

array([[0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.]])

In [28]:
df_train = pd.DataFrame()

Embarked
0        S
1        C
2        S
3        S
4        S
5        Q
6        S
7        S
8        S
9        C

In [32]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [0]:
#if we wanted to train a model here with 'Embarked', 'Sex' (both modified), 'Parch' and 'Fare', then we would have to repeat the one hot
#encoder process in the test data set because we can only test a model if it was trained with the same features. But we could have simplified
#this process by using a pipeline. 

# USING PIPELINES

In [0]:
cols = ['Parch','Fare', 'Embarked', 'Sex']

In [35]:
X = df[cols]
X

Parch     Fare Embarked     Sex
0      0   7.2500        S    male
1      0  71.2833        C  female
2      0   7.9250        S  female
3      0  53.1000        S  female
4      0   8.0500        S    male
5      0   8.4583        Q    male
6      0  51.8625        S    male
7      1  21.0750        S    male
8      2  11.1333        S  female
9      0  30.0708        C  female

In [0]:
ohe = OneHotEncoder()

In [0]:
from sklearn.compose import make_column_transformer

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder = 'passthrough'
)

In [40]:
ct.fit_transform(X)

array([[ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    ,  7.925 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    , 53.1   ],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  8.05  ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  8.4583],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    , 51.8625],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  1.    , 21.075 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 30.0708]])

In [0]:
from sklearn.pipeline import make_pipeline

In [0]:
pipe = make_pipeline(ct, logreg)

In [44]:
pipe.fit(X, y)
#first X (4 columns) gets transformed into 7 columns in ct (column transformer) process and then that produced matrix is entered into logreg.
#It's the same as having done logreg.fit(ct.fit_transform(X), y)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['Embarked', 'Sex'])],
                                   verbose=False)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                         

In [0]:
#on the image above we can see the two steps in the pipeline, first bulk of info is the ct step and second is the logreg

In [0]:
pipe.named_steps.logisticregression.coef_
#this returns the coefficients for each of the columns, assigned by logreg after fitting